ALTER TABLE NewAFRAAD.dbo.Followers ADD tripleNo varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Followers ADD Name varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Moving ADD TotalSpecified int NULL;
ALTER TABLE NewAFRAAD.dbo.Recommendations ADD tripleNo varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Recommendations ADD Name varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Soldier ADD ServiceType varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Soldier ADD GHA varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Soldier ADD DriverLevel varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Soldier ADD Treatment varchar(100) NULL;
ALTER TABLE NewAFRAAD.dbo.Soldier ALTER COLUMN ServiceType varchar(100) COLLATE Arabic_CI_AI NULL;
ALTER TABLE NewAFRAAD.dbo.Soldier ALTER COLUMN DriverLevel varchar(100) COLLATE Arabic_CI_AI NULL;
ALTER TABLE NewAFRAAD.dbo.Soldier ALTER COLUMN Treatment varchar(100) COLLATE Arabic_CI_AI NULL;
